/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package devoo.h4301.views;

import devoo.h4301.controller.ControleurPlan;
import devoo.h4301.controller.LecteurXml;
import devoo.h4301.model.Noeud;
import devoo.h4301.model.Troncon;

/**
 *
 * @author chouard
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    public ControleurPlan controleurPlan;
    
    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanePlan = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPanePlan, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanePlan, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FenetrePrincipale fp = new FenetrePrincipale();
                fp.setVisible(true);
                fp.controleurPlan = new ControleurPlan(fp.scrollPanePlan, fp);
        
//                LecteurXml lec = new LecteurXml();
//                lec.construirePlanAPartirXML();

                Noeud n0 = new Noeud(0, 200, 200);
                Noeud n1 = new Noeud(0, 100, 100);
                Noeud n2 = new Noeud(0, 150, 100);
                Noeud n3 = new Noeud(0, 200, 100);
                Noeud n4 = new Noeud(0, 250, 100);
                Noeud n5 = new Noeud(0, 300, 100);
                Noeud n6 = new Noeud(0, 300, 150);
                Noeud n7 = new Noeud(0, 300, 200);
                Noeud n8 = new Noeud(0, 300, 250);
                Noeud n9 = new Noeud(0, 300, 300);
                Noeud n10 = new Noeud(0, 250, 300);
                Noeud n11 = new Noeud(0, 200, 300);
                Noeud n12 = new Noeud(0, 150, 300);
                Noeud n13 = new Noeud(0, 100, 300);
                Noeud n14 = new Noeud(0, 100, 250);
                Noeud n15 = new Noeud(0, 100, 200);
                Noeud n16 = new Noeud(0, 100, 150);
                fp.controleurPlan.addNoeud(n0);
                fp.controleurPlan.addNoeud(n1);
                fp.controleurPlan.addNoeud(n2);
                fp.controleurPlan.addNoeud(n3);
                fp.controleurPlan.addNoeud(n4);
                fp.controleurPlan.addNoeud(n5);
                fp.controleurPlan.addNoeud(n6);
                fp.controleurPlan.addNoeud(n7);
                fp.controleurPlan.addNoeud(n8);
                fp.controleurPlan.addNoeud(n9);
                fp.controleurPlan.addNoeud(n10);
                fp.controleurPlan.addNoeud(n11);
                fp.controleurPlan.addNoeud(n12);
                fp.controleurPlan.addNoeud(n13);
                fp.controleurPlan.addNoeud(n14);
                fp.controleurPlan.addNoeud(n15);
                fp.controleurPlan.addNoeud(n16);
                
                Troncon t1 = new Troncon(n0, n1, "t1", 20.5, 1.5);
                Troncon t2 = new Troncon(n0, n2, "t2", 20.5, 1.5);
                Troncon t3 = new Troncon(n0, n3, "t3", 20.5, 1.5);
                Troncon t4 = new Troncon(n0, n4, "t4", 20.5, 1.5);
                Troncon t5 = new Troncon(n0, n5, "t5", 20.5, 1.5);
                Troncon t6 = new Troncon(n0, n6, "t6", 20.5, 1.5);
                Troncon t7 = new Troncon(n0, n7, "t7", 20.5, 1.5);
                Troncon t8 = new Troncon(n0, n8, "t8", 20.5, 1.5);
                Troncon t9 = new Troncon(n0, n9, "t9", 20.5, 1.5);
                Troncon t10 = new Troncon(n0, n10, "t10", 20.5, 1.5);
                Troncon t11 = new Troncon(n0, n11, "t11", 20.5, 1.5);
                Troncon t12 = new Troncon(n0, n12, "t12", 20.5, 1.5);
                Troncon t13 = new Troncon(n0, n13, "t13", 20.5, 1.5);
                Troncon t14 = new Troncon(n0, n14, "t14", 20.5, 1.5);
                Troncon t15 = new Troncon(n0, n15, "t15", 20.5, 1.5);
                Troncon t16 = new Troncon(n0, n16, "t16", 20.5, 1.5);

                fp.controleurPlan.addTroncon(t1);
                fp.controleurPlan.addTroncon(t2);
                fp.controleurPlan.addTroncon(t3);
                fp.controleurPlan.addTroncon(t4);
                fp.controleurPlan.addTroncon(t5);
                fp.controleurPlan.addTroncon(t6);
                fp.controleurPlan.addTroncon(t7);
                fp.controleurPlan.addTroncon(t8);
                fp.controleurPlan.addTroncon(t9);
                fp.controleurPlan.addTroncon(t10);
                fp.controleurPlan.addTroncon(t11);
                fp.controleurPlan.addTroncon(t12);
                fp.controleurPlan.addTroncon(t13);
                fp.controleurPlan.addTroncon(t14);
                fp.controleurPlan.addTroncon(t15);
                fp.controleurPlan.addTroncon(t16);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPanePlan;
    // End of variables declaration//GEN-END:variables
}
