/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package devoo.h4301.views;

import devoo.h4301.controller.ControleurLivraison;
import devoo.h4301.model.Livraison;
import java.awt.Dimension;

/**
 *
 * @author Mimi
 */
public class VueLivraisonItem extends javax.swing.JPanel {
    
    private Livraison livraison;
    private ControleurLivraison controleurLivraison;

    /**
     * Create new form VueLivraison 
     */
    public VueLivraisonItem(){
        initialize();
    }
    
    /**
     * Creates new form VueLivraison
     */
    public VueLivraisonItem(Livraison livraison, ControleurLivraison controleurLivraison) {
        this.setLivraison(livraison);
        this.setControleurLivraison(controleurLivraison);
        initialize();
    }
    
    public void initialize() {
        initComponents();
        
        this.setPreferredSize(new Dimension(280, 150));
        
        this.setOpaque(false);
        this.setVisible(true);
    }
    
    public Livraison getLivraison() {
        return livraison;
    }

     public void setLivraison(Livraison liv){
        this.livraison = liv;
        
        this.idClient.setText("cookie");
    }

    public ControleurLivraison getControleurLivraison() {
        return controleurLivraison;
    }

    public void setControleurLivraison(ControleurLivraison controleurLivraison) {
        this.controleurLivraison = controleurLivraison;
    }
     
   /* @Override
    public void paintCoponent()
    {
    
    }
     */
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idClient = new javax.swing.JLabel();
        nomClient = new javax.swing.JLabel();
        plageHoraire = new javax.swing.JLabel();
        supprBouton = new javax.swing.JButton();

        setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        setPreferredSize(new java.awt.Dimension(280, 50));

        idClient.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        idClient.setText("[1]");

        nomClient.setText("Nom Client");

        plageHoraire.setText("Plage horaire");

        supprBouton.setText("Suppr");
        supprBouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprLiv(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomClient)
                    .addComponent(plageHoraire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(supprBouton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idClient)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(nomClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(plageHoraire)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(supprBouton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void supprLiv(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprLiv
        this.controleurLivraison.supprLiv(this.livraison);
    }//GEN-LAST:event_supprLiv


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idClient;
    private javax.swing.JLabel nomClient;
    private javax.swing.JLabel plageHoraire;
    private javax.swing.JButton supprBouton;
    // End of variables declaration//GEN-END:variables
}
