/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package devoo.h4301.views;

import devoo.h4301.controller.ControleurLivraison;
import devoo.h4301.model.Livraison;
import devoo.h4301.model.Tournee;
import java.awt.Dimension;
import java.util.LinkedList;

/**
 *
 * @author Mimi
 */
public class VueListLivraison extends javax.swing.JPanel {
    private final ControleurLivraison controleurLivraison;
   
    private final LinkedList<VueLivraisonItem> vueLivraisonsItem = new LinkedList();
    
    /**
     * Creates new form VueLivraisonItem
     * @param controleurLivraison
     */
    public VueListLivraison(ControleurLivraison controleurLivraison) {
        this.controleurLivraison = controleurLivraison; 
        initialize();
    }
    
    public void initialize() {
        initComponents();
        
        this.setOpaque(false);
        this.setVisible(true); 
    }
    
    public void reset() {
        this.removeAll();
        this.updateUI();
        this.vueLivraisonsItem.clear();
    }
    
    public void ajouterLivraison(Livraison livraison) {
        VueLivraisonItem v = new VueLivraisonItem(this.controleurLivraison, livraison);
        this.vueLivraisonsItem.add(v);
        
        this.placerLivraison(v, this.vueLivraisonsItem.size()-1);
        this.updateVueListLivraison();
        
        this.add(v);
        v.setVisible(true);
    }
    
      private void updateVueListLivraison() {
        int listHeight = 50 * this.vueLivraisonsItem.size();
        
        Dimension dimension = new Dimension(280, listHeight);
        this.setPreferredSize(dimension);
    }
    
    public void placerLivraison(VueLivraisonItem vl, int rank) {
        vl.setSize(280, 150);
        
        int yLocation = rank * 50;
        vl.setLocation(0, yLocation);
    }

    public LinkedList<VueLivraisonItem> getVueLivraison() {
        return vueLivraisonsItem;
    }

    public ControleurLivraison getControleurLivraison() {
        return controleurLivraison;
    }

    public void setTournee(Tournee tournee) {
        this.vueLivraisonsItem.clear();
        for(int i = 0; i < tournee.getLivraisons().size(); i++)
        {
            this.ajouterLivraison(tournee.getLivraisons().get(i));
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(280, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
