/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package devoo.h4301.views;

import devoo.h4301.model.Noeud;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author chouard
 */
public class VueNoeud extends javax.swing.JPanel {
    
    protected Noeud noeud;
    protected VuePlan vuePlan;
    
    protected boolean selected;
    protected boolean hovered;
    
    /**
     * Creates new form VueNoeud
     */
    public VueNoeud() {
        initialize();
    }
    
    /**
     * Constructeur VueNoeud avec création du noeud
     */
    public VueNoeud(Noeud noeud, VuePlan vuePlan) {
        this.setNoeud(noeud);
        this.setVuePlan(vuePlan);
        initialize();
    }
    
    protected void initialize() {
        initComponents();

        this.setOpaque(false);
        this.setVisible(true); 
    }

    public Noeud getNoeud() {
        return noeud;
    }

    public void setNoeud(Noeud noeud) {
        this.noeud = noeud;
    }
    
    public int getXNoeud() {
        return this.noeud.getX();
    }
    
    public int getYNoeud() {
        return this.noeud.getY();
    }

    public VuePlan getVuePlan() {
        return vuePlan;
    }

    public void setVuePlan(VuePlan vuePlan) {
        this.vuePlan = vuePlan;
    }

    public boolean isSelected() {
        return selected;
    }

    public boolean isHovered() {
        return hovered;
    }
    
    public void setSelected(boolean selected) {
        this.selected = selected;
        
        if (selected) {
            this.vuePlan.createLiv(this.noeud);
        }
        
        this.repaint();
    }
    
    public void setHovered(boolean hovered) {
        this.hovered = hovered;
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        this.repaint();
    }
    
    public Color getColor() {
        if (this.selected || this.hovered) {
            return VuePlan.rougeMaps;
        } else {
            return VuePlan.grisMaps;
        }
    }
    
    @Override
    public void paintComponent(Graphics g)
    {
        Graphics2D graphics = (Graphics2D) g;
//        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        super.paintComponent(g);
        g.setColor(this.getColor());
        g.fillOval(0,0,this.getWidth(),this.getHeight());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClick(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onOut(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onHover(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClick
        this.setSelected(!this.selected);
    }//GEN-LAST:event_onClick

    private void onHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onHover
        this.setHovered(true);
    }//GEN-LAST:event_onHover

    private void onOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onOut
        this.setHovered(false);
    }//GEN-LAST:event_onOut


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
