/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package devoo.h4301.views;

import devoo.h4301.model.Noeud;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author chouard
 */
public class VueNoeud extends javax.swing.JPanel {
    
    private Noeud noeud;
    
    private final Color rougeMaps = new Color(217, 95, 87);
    
    public static int diamNoeud = 15;
    
    /**
     * Creates new form VueNoeud
     */
    public VueNoeud() {
        initialize();
    }
    
    /**
     * Constructeur VueNoeud avec création du noeud
     */
    public VueNoeud(Noeud noeud) {
        this.setNoeud(noeud);
        initialize();
    }
    
    private void initialize() {
        initComponents();

        this.setOpaque(false);
        this.setVisible(true); 
    }

    public Noeud getNoeud() {
        return noeud;
    }

    public void setNoeud(Noeud noeud) {
        this.noeud = noeud;
        
        this.reloadNoeud();
    }
    
    public void reloadNoeud() {
        this.setSize(diamNoeud, diamNoeud);
        
        int x = this.noeud.getX() - this.getWidth()/2;
        int y = this.noeud.getY() - this.getHeight()/2;
        this.setLocation(x, y);
    }
    
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.setColor(rougeMaps);
        g.fillOval(0,0,this.getWidth(),this.getHeight());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
