/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package devoo.h4301.views;

import devoo.h4301.model.Troncon;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author chouard
 */
public class VueTroncon extends javax.swing.JPanel {
    
    private Troncon troncon;
    
    private final Color jauneMaps = new Color(248, 228, 122);
    private final Color blancMaps = new Color(255, 255, 255);
    
    private static int diamNoeud = VueNoeud.diamNoeud;
    private static int largeurTrait = 4;
    private static int hautMin = 4;
    private static int largMin = 4;
    /**
     * Creates new form VueTroncon
     */
    public VueTroncon() {
        initialize();
    }
    
    /**
     * Constructeur VueTroncon avec création du troncon
     */
    public VueTroncon(Troncon troncon) {
        this.setTroncon(troncon);
        initialize();
    }
    
    private void initialize() {
        initComponents();

        this.setOpaque(false);
        this.setVisible(true);
        this.setBackground(jauneMaps); 
    }

    public Troncon getTroncon() {
        return troncon;
    }

    public void setTroncon(Troncon troncon) {
        this.troncon = troncon;
        
        this.reloadTroncon();
    }
    
    public void reloadTroncon() {
        int larg = Math.abs(troncon.getDestination().getX() - troncon.getOrigine().getX());
        int haut = Math.abs(troncon.getDestination().getY() - troncon.getOrigine().getY());
        if (larg < largMin) {
            larg = largMin;
        }
        if (haut < hautMin) {
            haut = hautMin;
        }
        
        int x = Math.min(troncon.getOrigine().getX(), troncon.getDestination().getX()) - largeurTrait/2;
        int y = Math.min(troncon.getOrigine().getY(), troncon.getDestination().getY()) - largeurTrait/2;
        
        if (   (troncon.getDestination().getX() > troncon.getOrigine().getX()) && (troncon.getDestination().getY() < troncon.getOrigine().getY())
            || (troncon.getDestination().getX() < troncon.getOrigine().getX()) && (troncon.getDestination().getY() > troncon.getOrigine().getY())
        ) {
            x -= diamNoeud/2;
            y -= diamNoeud/2;
            larg += diamNoeud/2;
            haut += diamNoeud/2;
        }
        
        this.setSize(larg, haut);
        this.setLocation(x, y);
    }
   
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.setColor(jauneMaps);
        Graphics2D g2D = (Graphics2D) g;
        g2D.setStroke(new BasicStroke(largeurTrait));
        
        int xDepart, yDepart, xArrivee, yArrivee;
        
        if (this.getWidth() <= largMin) {
            xDepart = largMin/2;
            xArrivee = largMin/2;
        } else if (this.getTroncon().getOrigine().getX() > this.getTroncon().getDestination().getX()) {
            xDepart = this.getWidth() + diamNoeud/2;
            xArrivee = diamNoeud/2;
        } else {
            xDepart = diamNoeud/2;
            xArrivee = this.getWidth() + diamNoeud/2;
        }
        
        if (this.getHeight() <= hautMin) {
            yDepart = hautMin/2;
            yArrivee = hautMin/2;
        } else if (this.getTroncon().getOrigine().getY() > this.getTroncon().getDestination().getY()) {
            yDepart = this.getHeight() + diamNoeud/2;
            yArrivee = diamNoeud/2;
        } else {
            yDepart = diamNoeud/2;
            yArrivee = this.getHeight() + diamNoeud/2;
        }
        
        g.drawLine(xDepart, yDepart, xArrivee, yArrivee);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
