/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package devoo.h4301.views;

import devoo.h4301.model.Troncon;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author chouard
 */
public class VueTroncon extends javax.swing.JPanel {
    
    private Troncon troncon;
    
    /**
     * Creates new form VueTroncon
     */
    public VueTroncon() {
        initialize();
    }
    
    /**
     * Constructeur VueTroncon avec création du troncon
     */
    public VueTroncon(Troncon troncon) {
        this.setTroncon(troncon);
        initialize();
    }
    
    private void initialize() {
        initComponents();

        this.setOpaque(true);
        this.setVisible(true);
        this.setBackground(Color.BLACK); 
    }

    public Troncon getTroncon() {
        return troncon;
    }

    public void setTroncon(Troncon troncon) {
        this.troncon = troncon;
    }
   
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.setColor(VuePlan.jauneMaps);
        Graphics2D g2D = (Graphics2D) g;
        g2D.setStroke(new BasicStroke(VuePlan.largeurTraitTroncon));
        
        int xDepart, yDepart, xArrivee, yArrivee;
        
        if (this.getWidth() <= VuePlan.xMinTroncon) {
            xDepart = VuePlan.xMinTroncon/2;
            xArrivee = VuePlan.xMinTroncon/2;
        } else if (this.getTroncon().getOrigine().getX() > this.getTroncon().getDestination().getX()) {
            xDepart = this.getWidth() + VuePlan.diamNoeud/2;
            xArrivee = VuePlan.diamNoeud/2;
        } else {
            xDepart = VuePlan.diamNoeud/2;
            xArrivee = this.getWidth() + VuePlan.diamNoeud/2;
        }
        
        if (this.getHeight() <= VuePlan.yMinTroncon) {
            yDepart = VuePlan.yMinTroncon/2;
            yArrivee = VuePlan.yMinTroncon/2;
        } else if (this.getTroncon().getOrigine().getY() > this.getTroncon().getDestination().getY()) {
            yDepart = this.getHeight() + VuePlan.diamNoeud/2;
            yArrivee = VuePlan.diamNoeud/2;
        } else {
            yDepart = VuePlan.diamNoeud/2;
            yArrivee = this.getHeight() + VuePlan.diamNoeud/2;
        }
        
        g.drawLine(xDepart, yDepart, xArrivee, yArrivee);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
